### ISSUE TITLE
nginx 403

### ISSUE THREAD

**Issue by vladislavs1321** [intellectsoft-uk/symfony-skeleton#11]
Hello.

How to solve this problem?

![screen shot 2016-02-24 at 13 02 19](https://cloud.githubusercontent.com/assets/2521819/13281848/247afc8c-daf7-11e5-93b4-d1e91202de25.png)

**Comment by fesor** [comment]
@vladislavs1321 you need something in your webroot. If you look at `front/config/conf.d/default.conf`, then you'll see that not all requests triggers PHP.
