### ISSUE TITLE
Структура файлов DevOps

### ISSUE THREAD

**Issue by atom-azimov** [intellectsoft-uk/symfony-skeleton#28]
В ansible версии все что связано с DevOps находился в папке с соответствующем названием.

В докер версии все разбросано в папки support/front и докерфайл в корневом папке, почему не делаете как ansible версии?

**Comment by fesor** [comment]
Вопервых папки `support/front` уже давно нет, есть просто `front`. там могут жить например исходники фронтэнда. 

Во вторых это связано с ограничениями докера, а именно контекст. То есть Dockerfile должен лежать либо в корне либо выше, а это значит что нужно будет выносить все в какую-то директорию и в корне будут докерфайлы + конфиги + отдельная папка где уже будет лежать симфони. Лично мне так не нравится.

**Comment by atom-azimov** [comment]
Прощу прощения имелось ввиду, `support` и `front`

> То есть Dockerfile должен лежать либо в корне либо выше

Указывать `context` и `dockerfile` в `docker-compose.yml` не подходит? https://github.com/atom-azimov/treto-test/blob/master/docker-compose.yml

**Comment by fesor** [comment]
front - это часть исходников, там далеко не все относится к devops.

Вынести же все что относится к докеру в отдельную директорию - это мысль с одной стороны, с другой... как бы и смысла в этом не много.

**Comment by atom-azimov** [comment]
> front - это часть исходников, там далеко не все относится к devops.

Я в курсе, отчасти поэтому предлагаю вынести докеры в `devops`.
Ибо хочу чтобы исходный код и `devops`  держался отдельно, чтобы менять вторую было легче, к примеру, в этом же проекте раньше был ansible, сейчас docker, завтра кто знает.

**Comment by fesor** [comment]
> Я в курсе, отчасти поэтому предлагаю вынести докеры в devops.

то есть и docker-compose.yml? Тогда будут сложности, я хочу иметь возможность сделать git clone && docker-compose up -d и начать работать. А так мне придется еще либо просить разработчика в переменных окружения явно задать `COMPOSE_FILE=devops/docker-compose.yml`. И тогда другие проекты с docker-compose работать не будут... проще так.

Ну и опять же, ансибл - это ансибл. Это средство автоматизации провиженинга. Vagrantfile же лежал в корне проекта.

В целом, кому как удобнее. Как по мне если говорить об изменениях структуры больше профита я бы получил смерджив `app` и `src` вместе.

**Comment by atom-azimov** [comment]
> то есть и docker-compose.yml?

Нет, конечно. Только то что требуется для сборки образов + возможно `env` файлы.

Ещё есть некоторые мысли, но их проще показать.
Пожалуй, я лучше отправлю PR.

**Comment by fesor** [comment]
> + возможно env файлы.

если вы посмотрите, сейчас их нет. Все переменные окружения прописаны в docker-compose.yml а дефолтные значения в `.env` и лежать оно должно рядом, поскольку это фича docker-compose. А выносить два файлика в директорию и усложнять структуру я не вижу смысла.
