### ISSUE TITLE
Could not find package intellectsoft/backend-skeleton with stability stable

### ISSUE THREAD

**Issue by pasxel** [intellectsoft-uk/symfony-skeleton#34]
composer create-project intellectsoft/backend-skeleton .
                                                               
  [InvalidArgumentException]                                                    
  Could not find package intellectsoft/backend-skeleton with stability stable.

**Comment by snsanich** [comment]
What version of composer & php do you use?
Mine Composer version 1.2-dev (06c45623d76457562cecbcf2245f904aa0f63a87) 2016-05-26 16:11:16, 
PHP 7.0.4 (cli)

**Comment by pasxel** [comment]
Thank you, @snsanich
